project:
  type: website
  preview:
    port: 4200
  output-dir: spring2024

website:
  page-navigation: true
  title: "BEE 4850 - Spring 2024"
  description: "Homepage for BEE 4850/5850, Environmental Data Analysis and Simulation, at Cornell University, Spring 2024."
  site-url: "https://envdata.viveks.me/spring2024"

  repo-url: https://github.com/bee-envdata-cornell/spring2024/

  open-graph: true

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Vivek Srikrishnan</span><br>
      See the [About Page](/about.qmd) for credit information.
    center: 
      - text: "<a href='https://creativecommons.org/licenses/by-sa/4.0/deed.en'>LICENSE: CC-BY-SA {{< fa creative-commons-sa >}} <i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a>"
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  sidebar:
    style: docked
    align: center
    border: true
    logo: _assets/logos/cornell_logo_simple_b31b1b.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: https://github.com/bee-envdata-cornell/spring2024/
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.cornell.edu
        text: "Canvas"
      - icon: chat-fill
        text: "Ed Discussion"
        url: https://edstem.org
      - icon: bar-chart-fill
        text: "Gradescope"
        url: https://gradescope.com
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
          - href: syllabus.qmd
            text: Syllabus
          - href: schedule.qmd
            text: Class Schedule
          - href: policies/homework.qmd
            text: Homework Policies
      - section: "Weeks"
        contents:
          - href: weeks/week01.qmd
            text: Week 1
          - href: weeks/week02.qmd
            text: Week 2
          - href: weeks/week03.qmd
            text: Week 3
          - href: weeks/week04.qmd
            text: Week 4
          - href: weeks/week05.qmd
            text: Week 5
          - href: weeks/week06.qmd
            text: Week 6
          - href: weeks/week07.qmd
            text: Week 7
          - href: weeks/week08.qmd
            text: Week 8
          - href: weeks/week09.qmd
            text: Week 9
          - href: weeks/week10.qmd
            text: Week 10
          - href: weeks/week11.qmd
            text: Week 11
          - href: weeks/week12.qmd
            text: Week 12
          - href: weeks/week13.qmd
            text: Week 13
          - href: weeks/week14.qmd
            text: Week 14
      - section: homework.qmd
        text: "Homework"
        contents:
          - href: rubrics/standard.qmd
            text: Standard Rubric
          - href: assignments/hw01/hw01.qmd
            text: Homework 1
          - href: assignments/hw02/hw02.qmd
            text: Homework 2
          - href: assignments/hw03/hw03.qmd
            text: Homework 3
          - href: assignments/hw04/hw04.qmd
            text: Homework 4
      - section: exercises.qmd
        contents:
          - href: exercises/ex01/ex01.qmd
            text: Exercise 1
          - href: exercises/ex03/ex03.qmd
            text: Exercise 3
          - href: exercises/ex04/ex04.qmd
            text: Exercise 4
          - href: exercises/ex05/ex05.qmd
            text: Exercise 5
          - href: exercises/ex07/ex07.qmd
            text: Exercise 7
          - href: exercises/ex08/ex08.qmd
            text: Exercise 8
      - project.qmd
      - lit_review.qmd
      - section: "Julia Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/turing-mcmc.qmd
            text: MCMC with Turing
format:
  html:
    grid:
      gutter-width: 1em
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl
execute:
  freeze: auto
engine: julia
julia:
    exeflags: ['+1.10.4']

